### ISSUE TITLE
SDK & Tools section shows Nexmo content

### ISSUE THREAD

**Issue by bdorry** [Vonage/vbc-developer#26]
SDK & Tools content needs to be configurable and instructions provided

**Comment by bdorry** [comment]
@mheap is this page editable, and if so which template should be added/modified to the repo to edit it?

**Comment by mheap** [comment]
https://github.com/VonageGarage/VDP/blob/master/custom/landing_pages/tools.yml

**Comment by tbass134** [comment]
https://github.com/Vonage/vbc-developer/pull/78
